config/routes.rb
Blocmarks::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  # get "tags/index"
  # get 'tags/:tag', to: 'bookmarks#index', as: :tag
  # get 'tags', to: 'tags#index', as: :tag
  # get 'tags/:id', to: 'tags#show', as: :tag
  resources :tags, only: [:index, :show]
  resources :bookmarks

  root 'bookmarks#index'

 
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  acts_as_taggable
  default_scope { order('created_at DESC') }

  belongs_to :user
end

app/models/email_processor.rb
class EmailProcessor
  def self.process(email)  
    self.create_bookmark(email)
  end

  def self.create_bookmark(email)   
    if email.subject.include? ","
      email_subject = email.subject.split(",").collect {|s| s.strip}
      @title = email_subject.first
      @url = email_subject.last
    else
      @title = email.subject
      @url = email.subject
    end
    self.get_user_id(email)
    Bookmark.create!({ title: @title, url: @url, user_id: @user_id, tag_list: email.body })    
  end

  def self.get_user_id(email)
    @user_id = User.find_by_email(email.from).id
    # @user_id = user.id if user
  end
end


app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of :email

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    redirect_to login_url, alert: "Not authorize" if current_user.nil?
  end
  
  helper_method :current_user

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  respond_to :html, :js
  before_filter :authorize, only: [:edit, :update, :destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.create(bookmark_params)
    @bookmark.save!
    redirect_to action: 'index'
    flash[:notice] = "Bookmark created"
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.update_attributes(bookmark_params)
    flash[:notice] = "Bookmark updated"
    redirect_to action: 'index', notice: "bookmark updated"
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.destroy
      flash[:notice] = "Bookmark deleted"
    else
      flash[:error] = "Something went wrong"
    end

    respond_with(@bookmark) do |f|
      f.html { redirect_to action 'index'}
    end
  end

private

  def bookmark_params
    params.require(:bookmark).permit(:title, :url, :tag_list)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end




end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Bookmark.tag_counts
  end

  def show
    @bookmarks = Bookmark.tagged_with(params[:id])
    render 'bookmarks/index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thanks for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @tags = Bookmark.find_by(user_id: @user.id).tag_counts
    @bookmark = Bookmark.find_by(user_id: @user.id)
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark.html.haml
.bookmark{:id => "bookmark-#{bookmark.id}"}
  = link_to bookmark.title, "#{bookmark.url}"
  = link_to "edit", edit_bookmark_path(bookmark[:id])
  = link_to "delete", bookmark_path(bookmark[:id]), :method => :delete, remote: true
  - if not bookmark.tag_list.empty?
    .tags
      Tags: 
      = raw (bookmark.tag_list.map { |t| link_to t, tag_path(t) }.join(', '))

app/views/bookmarks/_form.html.haml
= form_for bookmark do |f|
  .field
    = f.label :title
    <br />
    = f.text_field :title
  
  .field
    = f.label :url
    <br />
    = f.text_field :url

  .field
    = f.label :tag_list, "Separate tags with commas"
    <br />
    = f.text_field :tag_list

  = f.submit "Save"

app/views/bookmarks/destroy.js.haml
- if @bookmark.destroyed?
  $(document.body).prepend("#{escape_javascript(render :partial => 'layouts/flash')}");
  $('#bookmark-#{@bookmark.id}').hide();
- else
  $alert("uh oh");

app/views/bookmarks/edit.html.haml
%h3 Edit a bookmark
= form_for :bookmark, url: bookmark_path, method: :patch do |f|
  .field
    = f.label :title
    <br />
    = f.text_field :title
  
  .field
    = f.label :url
    <br />
    = f.text_field :url

  .field
    = f.label :tag_list, "Separate tags with commas"
    <br />
    = f.text_field :tag_list

  = f.submit "Save"

app/views/bookmarks/index.html.haml
%h1 Bookmarks#index
%p 
  Here's a list of Blocmarks
  = link_to "Show All", bookmarks_path

= render @bookmarks

%h3 Create a new bookmark
= render partial: "bookmarks/form", locals: {bookmark: Bookmark.new}

%h3 List of all tags
- Bookmark.tag_counts_on(:tags).each do |tag|
  = link_to tag.name, tag_path(tag.name)

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/incoming_mails/new.html.erb
<h1>incoming_mails#show</h1>
<p>Find me in app/views/incoming_mails/new.html.erb</p>

app/views/layouts/_flash.html.haml
- flash.each do |k,v|
  %div{ :class => k }= v

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Blocmarks
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    #user_header
      - if current_user
        Logged in as
        = link_to current_user.email, user_path(current_user.id)
        = link_to "Log Out", logout_path, method: :delete
      - else
        = link_to "Sign Up", signup_path
        or
        = link_to "Log In", login_path
    = render "layouts/flash"
    = yield

app/views/tags/index.html.haml
%h1 Tags#index
%p Find me in app/views/tags/index.html.erb

%h3 List of all tags
- @tags.each do |tag|
  %h4= link_to tag.name, tag_path(tag.name)
  - Bookmark.tagged_with(tag.name).each do |bookmark|
    %p= link_to bookmark.title, "#{bookmark.url}"

app/views/users/new.html.haml
%h1 Sign Up

= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - @user.errors.full_messages.each do |message|
          %li = message
  .field
    = f.label :email
    <br />
    = f.text_field :email
  .field
    = f.label :password
    <br />
    = f.password_field :password
  .field
    = f.label :password_confirmation
    <br />
    = f.password_field :password_confirmation
  .actions
    = f.submit "Sign up"

app/views/users/show.html.haml
%h1 User Page

= render partial: "bookmarks/bookmark", locals: {bookmark: @bookmark}


- @tags.each do |tag|
  %h4= link_to tag.name, tag_path(tag.name)
  - Bookmark.tagged_with(tag.name).each do |bookmark|
    %p= link_to bookmark.title, "#{bookmark.url}"